<a href="https://colab.research.google.com/github/2303A52060/AI-Assistant/blob/main/Ai_Ass_Ass_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment Number:17.2

Lab 17 – AI for Data Processing: Data Cleaning and Preprocessing
Scripts

Task Description – 1(Student Academic Data Cleaning)

• Task:

Use AI assistance to generate a Python script that cleans and

prepares a student academic dataset for analysis.

Instructions:

• Handle missing values in marks, attendance, and department.

• Remove duplicate student records based on student ID.

• Standardize text fields such as department names.

• Encode categorical variables like gender and department.


Prompt:

Generate a Python script using pandas to clean a student academic dataset from a CSV file.  

Handle missing values in marks, attendance, and department columns appropriately.  

Remove duplicate records based on student ID and standardize department names (e.g., lowercase/uppercase consistency).  

Encode categorical variables such as gender and department and output a cleaned DataFrame ready for analysis.

In [3]:
import pandas as pd
import os

# Create a dummy CSV file for demonstration purposes if students.csv does not exist
# In a real scenario, you would have your 'students.csv' file ready.
if not os.path.exists('students.csv'):
    data = {
        'StudentID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 11],
        'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy', 'Alice', 'Kevin'],
        'Gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Female', 'Female', 'Male'],
        'Department': ['Computer Science', 'Physics', 'Mathematics', 'Computer Science', 'Biology', 'physics', 'Mathematics', 'Computer science', 'Biology', 'Chemistry', 'Computer Science', 'Mathematics'],
        'Marks': [85, 72, None, 91, 78, 65, 88, 95, 70, 81, 85, None],
        'Attendance': [90, 85, 70, None, 92, 80, 95, 88, None, 75, 90, 82]
    }
    df_dummy = pd.DataFrame(data)
    df_dummy.to_csv('students.csv', index=False)

# Load the student academic dataset
df = pd.read_csv("students.csv")
print("Original DataFrame head:")
display(df.head())
print("Original DataFrame info:")
df.info()

# --- 1. Handle missing values in marks, attendance, and department. ---
# Fill missing 'Marks' with the mean
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

# Fill missing 'Attendance' with the mean
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].mean())

# Fill missing 'Department' with 'Unknown'
df['Department'] = df['Department'].fillna('Unknown')

print("\nDataFrame after handling missing values:")
display(df.head())
df.info()

# --- 2. Remove duplicate student records based on student ID. ---
print(f"\nNumber of records before removing duplicates: {len(df)}")
df.drop_duplicates(subset=['StudentID'], keep='first', inplace=True)
print(f"Number of records after removing duplicates: {len(df)}")
print("DataFrame after removing duplicates:")
display(df.head())

# --- 3. Standardize text fields such as department names. ---
df['Department'] = df['Department'].str.title()
print("\nDataFrame after standardizing Department names:")
display(df['Department'].value_counts())

# --- 4. Encode categorical variables like gender and department. ---
# One-hot encode 'Gender'
df = pd.get_dummies(df, columns=['Gender'], prefix='Gender', drop_first=True)

# One-hot encode 'Department'
df = pd.get_dummies(df, columns=['Department'], prefix='Department')

print("\nFinal Cleaned and Encoded DataFrame head:")
display(df.head())
print("Final DataFrame info:")
df.info()

Original DataFrame head:

   StudentID     Name  Gender        Department  Marks  Attendance
0          1    Alice  Female  Computer Science   85.0        90.0
1          2      Bob    Male           Physics   72.0        85.0
2          3  Charlie    Male       Mathematics    NaN        70.0
3          4    David    Male  Computer Science   91.0         NaN
4          5      Eve  Female           Biology   78.0        92.0

Original DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   12 non-null     int64
 1   Name        12 non-null     object
 2   Gender      12 non-null     object
 3   Department  12 non-null     object
 4   Marks       10 non-null     float64
 5   Attendance  10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 708.0+ bytes

DataFrame after handling missing values:

   StudentID     Name  Gender        Department  Marks  Attendance
0          1    Alice  Female  Computer Science   85.0        90.0
1          2      Bob    Male           Physics   72.0        85.0
2          3  Charlie    Male       Mathematics   81.0        70.0
3          4    David    Male  Computer Science   91.0        84.7
4          5      Eve  Female           Biology   78.0        92.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   12 non-null     int64
 1   Name        12 non-null     object
 2   Gender      12 non-null     object
 3   Department  12 non-null     object
 4   Marks       12 non-null     float64
 5   Attendance  12 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 708.0+ bytes

Number of records before removing duplicates: 12
Number of records after removing duplicates: 11
DataFrame after removing duplicates:

   StudentID     Name  Gender        Department  Marks  Attendance
0          1    Alice  Female  Computer Science   85.0        90.0
1          2      Bob    Male           Physics   72.0        85.0
2          3  Charlie    Male       Mathematics   81.0        70.0
3          4    David    Male  Computer Science   91.0        84.7
4          5      Eve  Female           Biology   78.0        92.0

DataFrame after standardizing Department names:

Department
Computer Science    3
Mathematics         3
Physics             2
Biology             2
Chemistry           1
Name: count, dtype: int64

Final Cleaned and Encoded DataFrame head:

,StudentID,Name,Marks,Attendance,Gender_Male,Department_Biology,Department_Chemistry,Department_Computer Science,Department_Mathematics,Department_Physics
0,1,Alice,85.0,90.0,False,False,False,True,False,False
1,2,Bob,72.0,85.0,True,False,False,False,False,True
2,3,Charlie,81.0,70.0,True,False,False,False,True,False
3,4,David,91.0,84.7,True,False,False,True,False,False
4,5,Eve,78.0,92.0,False,True,False,False,False,False

Final DataFrame info:
<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 11
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   StudentID                    11 non-null     int64
 1   Name                         11 non-null     object
 2   Marks                        11 non-null     float64
 3   Attendance                   11 non-null     float64
 4   Gender_Male                  11 non-null     bool
 5   Department_Biology           11 non-null     bool
 6   Department_Chemistry         11 non-null     bool
 7   Department_Computer Science  11 non-null     bool
 8   Department_Mathematics       11 non-null     bool
 9   Department_Physics           11 non-null     bool
dtypes: bool(6), float64(2), int64(1), object(1)
memory usage: 506.0+ bytes

Task Description – 2 (Financial Transaction Data Preprocessing)

• Task:
Preprocess financial transaction data using AI-generated Python
code.

Instructions:

• Convert transaction date columns to datetime format.

• Create derived features such as transaction month and year.

• Normalize the transaction amount column.

• Identify and handle extreme transaction values.

Prompt:

Generate a Python script using pandas and sklearn to preprocess a financial transaction dataset from a CSV file.  
Convert transaction date columns into datetime format and extract new features such as month and year.

Normalize the transaction amount column using MinMaxScaler.  

Detect and handle extreme or outlier transaction values and return a cleaned, transformed DataFrame.

In [5]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import os

# Create a dummy CSV file for demonstration purposes if transactions.csv does not exist
if not os.path.exists('transactions.csv'):
    data = {
        'TransactionID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'CustomerID': [101, 102, 101, 103, 102, 104, 101, 105, 103, 104],
        'TransactionDate': ['2023-01-01', '2023-01-05', '2023-01-10', '2023-01-15', '2023-02-01', '2023-02-10', '2023-02-15', '2023-03-01', '2023-03-05', '2023-03-10'],
        'Amount': [150.75, 20.00, 300.50, 50.25, 120.00, 80.00, 10000.00, 60.50, 250.00, 15.00],
        'Category': ['Groceries', 'Utilities', 'Shopping', 'Dining', 'Groceries', 'Utilities', 'Investment', 'Dining', 'Shopping', 'Groceries']
    }
    transactions_df = pd.DataFrame(data)
    transactions_df.to_csv('transactions.csv', index=False)

# Load the financial transaction dataset
transactions = pd.read_csv('transactions.csv')

print("Original DataFrame head:")
display(transactions.head())
print("Original DataFrame info:")
transactions.info()

# --- 1. Convert transaction date columns to datetime format. ---
transactions['TransactionDate'] = pd.to_datetime(transactions['TransactionDate'])

print("\nDataFrame after converting 'TransactionDate' to datetime:")
display(transactions.head())
transactions.info()

# --- 2. Create derived features such as transaction month and year. ---
transactions['TransactionMonth'] = transactions['TransactionDate'].dt.month
transactions['TransactionYear'] = transactions['TransactionDate'].dt.year

print("\nDataFrame with derived month and year features:")
display(transactions.head())

# --- 3. Normalize the transaction amount column. ---
scaler = MinMaxScaler()
transactions['Amount_Normalized'] = scaler.fit_transform(transactions[['Amount']])

print("\nDataFrame with normalized 'Amount' column:")
display(transactions.head())

# --- 4. Identify and handle extreme transaction values. ---
# Identify outliers using the IQR method for 'Amount'
Q1 = transactions['Amount'].quantile(0.25)
Q3 = transactions['Amount'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = transactions[(transactions['Amount'] < lower_bound) | (transactions['Amount'] > upper_bound)]
print("\nIdentified Outliers (before handling):")
display(outliers)

# Handle outliers: Cap the extreme values
transactions['Amount_Capped'] = transactions['Amount'].clip(lower=lower_bound, upper=upper_bound)

print("\nDataFrame after capping extreme 'Amount' values:")
display(transactions.head())

print("\nFinal Preprocessed DataFrame head:")
display(transactions.head())
print("Final Preprocessed DataFrame info:")
transactions.info()

Original DataFrame head:

   TransactionID  CustomerID TransactionDate  Amount   Category
0              1         101      2023-01-01  150.75  Groceries
1              2         102      2023-01-05   20.00  Utilities
2              3         101      2023-01-10  300.50   Shopping
3              4         103      2023-01-15   50.25     Dining
4              5         102      2023-02-01  120.00  Groceries

Original DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   CustomerID       10 non-null     int64
 2   TransactionDate  10 non-null     object
 3   Amount           10 non-null     float64
 4   Category         10 non-null     object
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

DataFrame after converting 'TransactionDate' to datetime:

   TransactionID  CustomerID TransactionDate  Amount   Category
0              1         101      2023-01-01  150.75  Groceries
1              2         102      2023-01-05   20.00  Utilities
2              3         101      2023-01-10  300.50   Shopping
3              4         103      2023-01-15   50.25     Dining
4              5         102      2023-02-01  120.00  Groceries

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   CustomerID       10 non-null     int64
 2   TransactionDate  10 non-null     datetime64[ns]
 3   Amount           10 non-null     float64
 4   Category         10 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 532.0+ bytes

DataFrame with derived month and year features:

,TransactionID,CustomerID,TransactionDate,Amount,Category,TransactionMonth,TransactionYear
0,1,101,2023-01-01,150.75,Groceries,1,2023
1,2,102,2023-01-05,20.00,Utilities,1,2023
2,3,101,2023-01-10,300.50,Shopping,1,2023
3,4,103,2023-01-15,50.25,Dining,1,2023
4,5,102,2023-02-01,120.00,Groceries,2,2023

DataFrame with normalized 'Amount' column:

,TransactionID,CustomerID,TransactionDate,Amount,Category,TransactionMonth,TransactionYear,Amount_Normalized
0,1,101,2023-01-01,150.75,Groceries,1,2023,0.013595
1,2,102,2023-01-05,20.00,Utilities,1,2023,0.000501
2,3,101,2023-01-10,300.50,Shopping,1,2023,0.028593
3,4,103,2023-01-15,50.25,Dining,1,2023,0.003530
4,5,102,2023-02-01,120.00,Groceries,2,2023,0.010516

Identified Outliers (before handling):

,TransactionID,CustomerID,TransactionDate,Amount,Category,TransactionMonth,TransactionYear,Amount_Normalized
6,7,101,2023-02-15,10000.0,Investment,2,2023,1.0

DataFrame after capping extreme 'Amount' values:

,TransactionID,CustomerID,TransactionDate,Amount,Category,TransactionMonth,TransactionYear,Amount_Normalized,Amount_Capped
0,1,101,2023-01-01,150.75,Groceries,1,2023,0.013595,150.75
1,2,102,2023-01-05,20.00,Utilities,1,2023,0.000501,20.00
2,3,101,2023-01-10,300.50,Shopping,1,2023,0.028593,300.50
3,4,103,2023-01-15,50.25,Dining,1,2023,0.003530,50.25
4,5,102,2023-02-01,120.00,Groceries,2,2023,0.010516,120.00

Final Preprocessed DataFrame head:

,TransactionID,CustomerID,TransactionDate,Amount,Category,TransactionMonth,TransactionYear,Amount_Normalized,Amount_Capped
0,1,101,2023-01-01,150.75,Groceries,1,2023,0.013595,150.75
1,2,102,2023-01-05,20.00,Utilities,1,2023,0.000501,20.00
2,3,101,2023-01-10,300.50,Shopping,1,2023,0.028593,300.50
3,4,103,2023-01-15,50.25,Dining,1,2023,0.003530,50.25
4,5,102,2023-02-01,120.00,Groceries,2,2023,0.010516,120.00

Final Preprocessed DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   TransactionID      10 non-null     int64
 1   CustomerID         10 non-null     int64
 2   TransactionDate    10 non-null     datetime64[ns]
 3   Amount             10 non-null     float64
 4   Category           10 non-null     object
 5   TransactionMonth   10 non-null     int32
 6   TransactionYear    10 non-null     int32
 7   Amount_Normalized  10 non-null     float64
 8   Amount_Capped      10 non-null     float64
dtypes: datetime64[ns](1), float64(3), int32(2), int64(2), object(1)
memory usage: 772.0+ bytes

Task 3 – (Environmental Sensor Data Preparation)

• Task:

Clean and preprocess environmental sensor data using AI-assisted
scripts.

Instructions:

• Handle missing values in temperature, humidity, and
air_quality_index.

• Scale numerical features using standard scaling.

• Encode categorical fields such as sensor_status.

• Split the dataset into training and testing subsets.

Prompt:

Write a Python script to preprocess environmental sensor data from 'sensor_data.csv' using pandas and scikit-learn.

Handle missing values in temperature, humidity, and air_quality_index columns.
Encode the categorical column 'sensor_status' and apply standard scaling to numerical features.
Split the dataset into training and testing sets and display the processed output.

In [6]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
import os

# Create a dummy CSV file for demonstration purposes if sensor_data.csv does not exist
if not os.path.exists('sensor_data.csv'):
    data = {
        'SensorID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        'Timestamp': pd.to_datetime(['2023-01-01 10:00:00', '2023-01-01 10:05:00', '2023-01-01 10:10:00', '2023-01-01 10:15:00',
                                   '2023-01-01 10:20:00', '2023-01-01 10:25:00', '2023-01-01 10:30:00', '2023-01-01 10:35:00',
                                   '2023-01-01 10:40:00', '2023-01-01 10:45:00', '2023-01-01 10:50:00', '2023-01-01 10:55:00']),
        'temperature': [25.5, 25.1, None, 26.0, 25.8, 26.2, 25.9, None, 26.5, 26.1, 25.7, 26.3],
        'humidity': [60.2, 60.5, 61.0, 59.8, None, 60.0, 60.3, 60.8, 59.5, None, 61.2, 60.7],
        'air_quality_index': [45, None, 50, 48, 47, 52, 49, 51, None, 46, 53, 50],
        'sensor_status': ['Active', 'Active', 'Inactive', 'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active', 'Inactive', 'Active', 'Active']
    }
    sensor_df_dummy = pd.DataFrame(data)
    sensor_df_dummy.to_csv('sensor_data.csv', index=False)

# Load the environmental sensor data
df = pd.read_csv('sensor_data.csv')

print("Original DataFrame head:")
display(df.head())
print("Original DataFrame info:")
df.info()

# --- 1. Handle missing values in temperature, humidity, and air_quality_index. ---
# Using SimpleImputer for numerical columns with the mean strategy
imputer_mean = SimpleImputer(strategy='mean')
df[['temperature', 'humidity', 'air_quality_index']] = imputer_mean.fit_transform(df[['temperature', 'humidity', 'air_quality_index']])

print("\nDataFrame after handling missing values:")
display(df.head())
df.info()

# --- 2. Encode categorical fields such as sensor_status. ---
# One-hot encode 'sensor_status'
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
sensor_status_encoded = encoder.fit_transform(df[['sensor_status']])
sensor_status_df = pd.DataFrame(sensor_status_encoded, columns=encoder.get_feature_names_out(['sensor_status']))

# Drop the original 'sensor_status' column and concatenate the encoded columns
df = pd.concat([df.drop('sensor_status', axis=1), sensor_status_df], axis=1)

print("\nDataFrame after encoding 'sensor_status':")
display(df.head())

# --- 3. Scale numerical features using standard scaling. ---
# Identify numerical columns for scaling (excluding 'SensorID' and 'Timestamp' if they are not features, and the encoded columns)
numerical_cols = ['temperature', 'humidity', 'air_quality_index']

scaler = StandardScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

print("\nDataFrame after scaling numerical features:")
display(df.head())

# --- 4. Split the dataset into training and testing subsets. ---
# Assuming 'air_quality_index' is the target variable for a predictive task
# You might need to adjust 'target' and 'features' based on your specific task

# Drop non-feature columns like 'SensorID' and 'Timestamp' for model training
df_processed = df.drop(columns=['SensorID', 'Timestamp'], errors='ignore')

# Define features (X) and target (y)
# Example: predicting air_quality_index
X = df_processed.drop('air_quality_index', axis=1)
y = df_processed['air_quality_index']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nShape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("\nPreprocessed DataFrame for training (X_train head):")
display(X_train.head())
print("Preprocessed Target for training (y_train head):")
display(y_train.head())

Original DataFrame head:

,SensorID,Timestamp,temperature,humidity,air_quality_index,sensor_status
0,1,2023-01-01 10:00:00,25.5,60.2,45.0,Active
1,2,2023-01-01 10:05:00,25.1,60.5,NaN,Active
2,3,2023-01-01 10:10:00,NaN,61.0,50.0,Inactive
3,4,2023-01-01 10:15:00,26.0,59.8,48.0,Active
4,5,2023-01-01 10:20:00,25.8,NaN,47.0,Active

Original DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SensorID           12 non-null     int64
 1   Timestamp          12 non-null     object
 2   temperature        10 non-null     float64
 3   humidity           10 non-null     float64
 4   air_quality_index  10 non-null     float64
 5   sensor_status      12 non-null     object
dtypes: float64(3), int64(1), object(2)
memory usage: 708.0+ bytes

DataFrame after handling missing values:

,SensorID,Timestamp,temperature,humidity,air_quality_index,sensor_status
0,1,2023-01-01 10:00:00,25.50,60.2,45.0,Active
1,2,2023-01-01 10:05:00,25.10,60.5,49.1,Active
2,3,2023-01-01 10:10:00,25.91,61.0,50.0,Inactive
3,4,2023-01-01 10:15:00,26.00,59.8,48.0,Active
4,5,2023-01-01 10:20:00,25.80,60.4,47.0,Active

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SensorID           12 non-null     int64
 1   Timestamp          12 non-null     object
 2   temperature        12 non-null     float64
 3   humidity           12 non-null     float64
 4   air_quality_index  12 non-null     float64
 5   sensor_status      12 non-null     object
dtypes: float64(3), int64(1), object(2)
memory usage: 708.0+ bytes

DataFrame after encoding 'sensor_status':

,SensorID,Timestamp,temperature,humidity,air_quality_index,sensor_status_Active,sensor_status_Inactive
0,1,2023-01-01 10:00:00,25.50,60.2,45.0,1.0,0.0
1,2,2023-01-01 10:05:00,25.10,60.5,49.1,1.0,0.0
2,3,2023-01-01 10:10:00,25.91,61.0,50.0,0.0,1.0
3,4,2023-01-01 10:15:00,26.00,59.8,48.0,1.0,0.0
4,5,2023-01-01 10:20:00,25.80,60.4,47.0,1.0,0.0

DataFrame after scaling numerical features:

,SensorID,Timestamp,temperature,humidity,air_quality_index,sensor_status_Active,sensor_status_Inactive
0,1,2023-01-01 10:00:00,-1.156192e+00,-4.264014e-01,-1.819977,1.0,0.0
1,2,2023-01-01 10:05:00,-2.284184e+00,2.132007e-01,0.000000,1.0,0.0
2,3,2023-01-01 10:10:00,-1.001858e-14,1.279204e+00,0.399507,0.0,1.0
3,4,2023-01-01 10:15:00,2.537982e-01,-1.279204e+00,-0.488286,1.0,0.0
4,5,2023-01-01 10:20:00,-3.101978e-01,1.514882e-14,-0.932183,1.0,0.0

Shape of X_train: (9, 4)
Shape of X_test: (3, 4)
Shape of y_train: (9,)
Shape of y_test: (3,)

Preprocessed DataFrame for training (X_train head):

     temperature  humidity  sensor_status_Active  sensor_status_Inactive
8   1.663788e+00 -1.918806                   1.0                     0.0
5   8.177942e-01 -0.852803                   1.0                     0.0
2  -1.001858e-14  1.279204                   0.0                     1.0
1  -2.284184e+00  0.213201                   1.0                     0.0
11  1.099792e+00  0.639602                   1.0                     0.0

Preprocessed Target for training (y_train head):

8     0.000000
5     1.287301
2     0.399507
1     0.000000
11    0.399507
Name: air_quality_index, dtype: float64

Task 4 – (Real-Time Application: Smart City Traffic Data Cleaning)

• Scenario:
A smart city system collects traffic data from multiple sensors,
resulting in noisy and inconsistent records.

Requirements:

• Standardize road and location names.

• Fill missing traffic density values using appropriate statistical
methods.

• Remove duplicate sensor readings.

• Normalize speed and vehicle count metrics.

• Generate a brief summary comparing dataset quality before and
after cleaning

Prompt:

Write a Python script to clean and preprocess smart city traffic data from 'traffic_data.csv' using pandas.

Standardize road and location names, handle missing traffic density values, and remove duplicate records.

Normalize speed and vehicle count columns using appropriate scaling techniques.

Generate and display a summary comparing data quality before and after cleaning.

In [7]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import os

# Create a dummy CSV file for demonstration purposes if traffic_data.csv does not exist
if not os.path.exists('traffic_data.csv'):
    data = {
        'SensorID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 11],
        'Timestamp': pd.to_datetime(['2023-01-01 08:00:00', '2023-01-01 08:05:00', '2023-01-01 08:10:00', '2023-01-01 08:15:00',
                                   '2023-01-01 08:20:00', '2023-01-01 08:25:00', '2023-01-01 08:30:00', '2023-01-01 08:35:00',
                                   '2023-01-01 08:40:00', '2023-01-01 08:45:00', '2023-01-01 08:00:00', '2023-01-01 08:50:00']),
        'RoadName': ['Main St', 'Oak Ave', 'Main St', 'Elm Blvd', 'Oak Ave', 'Pine Rd', 'Elm Blvd', 'Main ST', 'Pine Rd', 'Oak Ave', 'Main St', 'Maple Dr'],
        'Location': ['Downtown', 'North', '  downTOWN', 'West', 'North', 'East', 'WEST  ', 'Downtown', 'East', 'North', 'Downtown', 'South'],
        'TrafficDensity': [75, 60, np.nan, 80, 55, 70, 85, 78, np.nan, 62, 75, 68],
        'Speed': [45, 55, 30, 50, 60, 40, 35, 48, 52, 58, 45, 50],
        'VehicleCount': [120, 80, 150, 90, 70, 110, 130, 125, 95, 85, 120, 100]
    }
    traffic_df_dummy = pd.DataFrame(data)
    traffic_df_dummy.to_csv('traffic_data.csv', index=False)

# Load the smart city traffic data
traffic = pd.read_csv('traffic_data.csv')

print("--- Original DataFrame Info and Statistics ---")
display(traffic.head())
traffic.info()
print("\nMissing values before cleaning:")
print(traffic.isnull().sum())
print("\nDuplicate records before cleaning:")
print(traffic.duplicated().sum())

# --- 1. Standardize road and location names. ---
traffic['RoadName'] = traffic['RoadName'].str.strip().str.title()
traffic['Location'] = traffic['Location'].str.strip().str.title()

# --- 2. Fill missing traffic density values using appropriate statistical methods. ---
# Using the mean for 'TrafficDensity'
traffic['TrafficDensity'] = traffic['TrafficDensity'].fillna(traffic['TrafficDensity'].mean())

# --- 3. Remove duplicate sensor readings. ---
# Considering 'SensorID', 'Timestamp', 'RoadName', 'Location' as identifiers for unique readings
initial_rows = len(traffic)
traffic.drop_duplicates(subset=['SensorID', 'Timestamp', 'RoadName', 'Location'], keep='first', inplace=True)
print(f"\nRemoved {initial_rows - len(traffic)} duplicate records.")

# --- 4. Normalize speed and vehicle count metrics. ---
scaler = MinMaxScaler()
traffic[['Speed_Normalized', 'VehicleCount_Normalized']] = scaler.fit_transform(traffic[['Speed', 'VehicleCount']])

print("\n--- Cleaned and Preprocessed DataFrame Info and Statistics ---")
display(traffic.head())
traffic.info()
print("\nMissing values after cleaning:")
print(traffic.isnull().sum())
print("\nDuplicate records after cleaning:")
print(traffic.duplicated().sum())

print("\n--- Summary of Data Quality Improvement ---")
print("1. Road and Location Names:")
print("   - Standardized to Title Case and stripped whitespace for consistency.")
print("2. Missing Values:")
print("   - 'TrafficDensity' missing values were filled with the mean of the column.")
print("3. Duplicate Records:")
print(f"   - {initial_rows - len(traffic)} duplicate records were identified and removed based on SensorID, Timestamp, RoadName, and Location.")
print("4. Normalization:")
print("   - 'Speed' and 'VehicleCount' columns were normalized using MinMaxScaler, creating 'Speed_Normalized' and 'VehicleCount_Normalized' columns.")

print("\n The dataset is now cleaned, standardized, and normalized, ready for further analysis or model training.")

--- Original DataFrame Info and Statistics ---

,SensorID,Timestamp,RoadName,Location,TrafficDensity,Speed,VehicleCount
0,1,2023-01-01 08:00:00,Main St,Downtown,75.0,45,120
1,2,2023-01-01 08:05:00,Oak Ave,North,60.0,55,80
2,3,2023-01-01 08:10:00,Main St,downTOWN,NaN,30,150
3,4,2023-01-01 08:15:00,Elm Blvd,West,80.0,50,90
4,5,2023-01-01 08:20:00,Oak Ave,North,55.0,60,70

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SensorID        12 non-null     int64
 1   Timestamp       12 non-null     object
 2   RoadName        12 non-null     object
 3   Location        12 non-null     object
 4   TrafficDensity  10 non-null     float64
 5   Speed           12 non-null     int64
 6   VehicleCount    12 non-null     int64
dtypes: float64(1), int64(3), object(3)
memory usage: 804.0+ bytes

Missing values before cleaning:
SensorID          0
Timestamp         0
RoadName          0
Location          0
TrafficDensity    2
Speed             0
VehicleCount      0
dtype: int64

Duplicate records before cleaning:
1

Removed 1 duplicate records.

--- Cleaned and Preprocessed DataFrame Info and Statistics ---

,SensorID,Timestamp,RoadName,Location,TrafficDensity,Speed,VehicleCount,Speed_Normalized,VehicleCount_Normalized
0,1,2023-01-01 08:00:00,Main St,Downtown,75.0,45,120,0.500000,0.625
1,2,2023-01-01 08:05:00,Oak Ave,North,60.0,55,80,0.833333,0.125
2,3,2023-01-01 08:10:00,Main St,Downtown,70.8,30,150,0.000000,1.000
3,4,2023-01-01 08:15:00,Elm Blvd,West,80.0,50,90,0.666667,0.250
4,5,2023-01-01 08:20:00,Oak Ave,North,55.0,60,70,1.000000,0.000

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 11
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   SensorID                 11 non-null     int64
 1   Timestamp                11 non-null     object
 2   RoadName                 11 non-null     object
 3   Location                 11 non-null     object
 4   TrafficDensity           11 non-null     float64
 5   Speed                    11 non-null     int64
 6   VehicleCount             11 non-null     int64
 7   Speed_Normalized         11 non-null     float64
 8   VehicleCount_Normalized  11 non-null     float64
dtypes: float64(3), int64(3), object(3)
memory usage: 880.0+ bytes

Missing values after cleaning:
SensorID                   0
Timestamp                  0
RoadName                   0
Location                   0
TrafficDensity             0
Speed                      0
VehicleCount               0
Speed_Normalized           0
VehicleCount_Normalized    0
dtype: int64

Duplicate records after cleaning:
0

--- Summary of Data Quality Improvement ---
1. Road and Location Names:
   - Standardized to Title Case and stripped whitespace for consistency.
2. Missing Values:
   - 'TrafficDensity' missing values were filled with the mean of the column.
3. Duplicate Records:
   - 1 duplicate records were identified and removed based on SensorID, Timestamp, RoadName, and Location.
4. Normalization:
   - 'Speed' and 'VehicleCount' columns were normalized using MinMaxScaler, creating 'Speed_Normalized' and 'VehicleCount_Normalized' columns.

 The dataset is now cleaned, standardized, and normalized, ready for further analysis or model training.

ask 5 – (Social Media Text Data Cleaning and Feature Extraction)

• Task:

Use AI-assisted Python scripting to clean and preprocess social
media text data for sentiment analysis.

Instructions:

• Remove duplicate posts and null text entries.

• Clean text by removing URLs, special characters, and extra
spaces.

• Convert text to lowercase and perform basic tokenization.

• Remove stopwords and perform stemming or lemmatization.

• Generate basic text features such as word count and sentiment
score.

Prompt:

Write a Python script using pandas, NLTK, and regex to preprocess social media text data for sentiment analysis.

Remove duplicate posts and null text entries, and clean the text by removing URLs, special characters, and extra spaces.

Convert text to lowercase, tokenize it, remove stopwords, and apply stemming or lemmatization.

Generate features like word count and sentiment score, and output the cleaned dataset.

In [12]:
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from textblob import TextBlob
import os

# Download necessary NLTK data (if not already downloaded)
nltk.download('stopwords', quiet=True)
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True) # Unconditionally download punkt_tab to resolve persistent LookupError

# Create a dummy CSV file for demonstration purposes if social_media_posts.csv does not exist
if not os.path.exists('social_media_posts.csv'):
    data = {
        'PostID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 11],
        'Author': ['UserA', 'UserB', 'UserA', 'UserC', 'UserD', 'UserE', 'UserF', 'UserG', 'UserH', 'UserI', 'UserA', 'UserJ'],
        'Text': [
            'This is an amazing product! Highly recommend. #awesome #product https://example.com/p1',
            'Feeling great today! The weather is perfect. :-)',
            'This is an amazing product! Highly recommend. #awesome #product https://example.com/p1',
            'Just bought a new gadget. It\'s okay. Not too impressed.',
            'Worst experience ever. So disappointed. Avoid! 😡',
            'Loving the new update. Very smooth and efficient.',
            'Some neutral content here.',
            'I had a fantastic time at the event. 🎉',
            'Absolutely terrible service. Will not use again.',
            'Happy with my purchase. Worth every penny.',
            None, # Missing text entry
            'Having a good day!'
        ],
        'Timestamp': pd.to_datetime(['2023-01-01 10:00:00', '2023-01-01 10:05:00', '2023-01-01 10:00:00', '2023-01-01 10:15:00',
                                   '2023-01-01 10:20:00', '2023-01-01 10:25:00', '2023-01-01 10:30:00', '2023-01-01 10:35:00',
                                   '2023-01-01 10:40:00', '2023-01-01 10:45:00', '2023-01-01 10:00:00', '2023-01-01 10:50:00'])
    }
    posts_dummy = pd.DataFrame(data)
    posts_dummy.to_csv('social_media_posts.csv', index=False)

# Load the social media posts dataset
posts = pd.read_csv('social_media_posts.csv')

print("Original DataFrame head:")
display(posts.head())
print("Original DataFrame info:")
posts.info()
print(f"\nNumber of records before cleaning: {len(posts)}")

# --- 1. Remove duplicate posts and null text entries. ---
initial_rows = len(posts)
posts.drop_duplicates(subset=['PostID', 'Text'], keep='first', inplace=True)
posts.dropna(subset=['Text'], inplace=True)
print(f"Number of records after removing duplicates and nulls: {len(posts)}")

# --- 2. Clean text by removing URLs, special characters, and extra spaces. ---
# --- 3. Convert text to lowercase and perform basic tokenization. ---
# --- 4. Remove stopwords and perform stemming or lemmatization. ---

stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def clean_text(text):
    text = str(text).lower() # Convert to lowercase
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE) # Remove URLs
    text = re.sub(r'[^\w\s]', '', text) # Remove special characters
    text = re.sub(r'\s+', ' ', text).strip() # Remove extra spaces
    return text

def tokenize_and_process(text):
    tokens = nltk.word_tokenize(text) # Tokenization
    # Remove stopwords and apply stemming
    processed_tokens = [stemmer.stem(word) for word in tokens if word not in stop_words]
    return ' '.join(processed_tokens)

# Apply cleaning and processing functions
posts['Cleaned_Text'] = posts['Text'].apply(clean_text)
posts['Processed_Text'] = posts['Cleaned_Text'].apply(tokenize_and_process)

print("\nDataFrame after text cleaning and processing:")
display(posts[['Text', 'Cleaned_Text', 'Processed_Text']].head())

# --- 5. Generate basic text features such as word count and sentiment score. ---

# Word Count
posts['Word_Count'] = posts['Processed_Text'].apply(lambda x: len(x.split()))

# Sentiment Score using TextBlob
def get_sentiment(text):
    analysis = TextBlob(text)
    # Return sentiment polarity (-1 to 1, where -1 is negative, 0 is neutral, 1 is positive)
    return analysis.sentiment.polarity

posts['Sentiment_Score'] = posts['Cleaned_Text'].apply(get_sentiment)

print("\nFinal Cleaned DataFrame with Features:")
display(posts.head())
print("\nFinal DataFrame Info with new features:")
posts.info()

Original DataFrame head:

,PostID,Author,Text,Timestamp
0,1,UserA,This is an amazing product! Highly recommend. ...,2023-01-01 10:00:00
1,2,UserB,Feeling great today! The weather is perfect. :-),2023-01-01 10:05:00
2,3,UserA,This is an amazing product! Highly recommend. ...,2023-01-01 10:00:00
3,4,UserC,Just bought a new gadget. It's okay. Not too i...,2023-01-01 10:15:00
4,5,UserD,Worst experience ever. So disappointed. Avoid! 😡,2023-01-01 10:20:00

Original DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PostID     12 non-null     int64
 1   Author     12 non-null     object
 2   Text       11 non-null     object
 3   Timestamp  12 non-null     object
dtypes: int64(1), object(3)
memory usage: 516.0+ bytes

Number of records before cleaning: 12
Number of records after removing duplicates and nulls: 11

DataFrame after text cleaning and processing:

,Text,Cleaned_Text,Processed_Text
0,This is an amazing product! Highly recommend. ...,this is an amazing product highly recommend aw...,amaz product highli recommend awesom product
1,Feeling great today! The weather is perfect. :-),feeling great today the weather is perfect,feel great today weather perfect
2,This is an amazing product! Highly recommend. ...,this is an amazing product highly recommend aw...,amaz product highli recommend awesom product
3,Just bought a new gadget. It's okay. Not too i...,just bought a new gadget its okay not too impr...,bought new gadget okay impress
4,Worst experience ever. So disappointed. Avoid! 😡,worst experience ever so disappointed avoid,worst experi ever disappoint avoid

Final Cleaned DataFrame with Features:

,PostID,Author,Text,Timestamp,Cleaned_Text,Processed_Text,Word_Count,Sentiment_Score
0,1,UserA,This is an amazing product! Highly recommend. ...,2023-01-01 10:00:00,this is an amazing product highly recommend aw...,amaz product highli recommend awesom product,6,0.586667
1,2,UserB,Feeling great today! The weather is perfect. :-),2023-01-01 10:05:00,feeling great today the weather is perfect,feel great today weather perfect,5,0.900000
2,3,UserA,This is an amazing product! Highly recommend. ...,2023-01-01 10:00:00,this is an amazing product highly recommend aw...,amaz product highli recommend awesom product,6,0.586667
3,4,UserC,Just bought a new gadget. It's okay. Not too i...,2023-01-01 10:15:00,just bought a new gadget its okay not too impr...,bought new gadget okay impress,5,0.545455
4,5,UserD,Worst experience ever. So disappointed. Avoid! 😡,2023-01-01 10:20:00,worst experience ever so disappointed avoid,worst experi ever disappoint avoid,5,-0.875000

Final DataFrame Info with new features:
<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 11
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PostID           11 non-null     int64
 1   Author           11 non-null     object
 2   Text             11 non-null     object
 3   Timestamp        11 non-null     object
 4   Cleaned_Text     11 non-null     object
 5   Processed_Text   11 non-null     object
 6   Word_Count       11 non-null     int64
 7   Sentiment_Score  11 non-null     float64
dtypes: float64(1), int64(2), object(5)
memory usage: 792.0+ bytes